# Generated by Django 5.2.6 on 2025-09-21 01:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1886), django.core.validators.MaxValueValidator(2025)])),
                ('color', models.CharField(max_length=50)),
                ('availability', models.BooleanField(default=True)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('location', models.CharField(max_length=100)),
                ('image_url', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('power', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('system', models.CharField(choices=[('Gasolina', 'Gasolina'), ('Diesel', 'Diesel'), ('Electrónico', 'Electrónico'), ('Híbrido', 'Híbrido')], max_length=20)),
                ('accompanists', models.IntegerField(choices=[(2, '2'), (4, '4'), (5, '5'), (7, '7')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'autos',
            },
        ),
    ]
